In [ ]:

1. Импорт библиотеки NumPy с общепринятым сокращением.


In [ ]:
import numpy as np

In [ ]:
2. Примеры создания массивов:

In [4]:
import numpy as np
list_array=np.array([1,2,3,4,5]) #создание массива из списка
print(list_array)

[1 2 3 4 5]


In [6]:
import numpy as np
zeros_array=np.zeros(5) # создание массива с помощью zeros
print(zeros_array)

[0. 0. 0. 0. 0.]


In [8]:
import numpy as np
ones_array=np.ones(5) # создание массива с помощтю zeros
print(ones_array)

[1. 1. 1. 1. 1.]


In [9]:
import numpy as np
arange_array=np.arange(5) # создание массива с помощью arange
print(arange_array)

[0 1 2 3 4]


In [ ]:
3. Демонстрация атрибутов:

In [34]:
import numpy as np
demo_array=np.array([1,2,3,4],dtype=int) # создание массива и указ типа данных
print(demo_array)
print(demo_array.shape) # форма 
print(demo_array.dtype) # тип данных 

[1 2 3 4]
(4,)
int64


In [ ]:
4. Примеры индексирования и срезов:

In [33]:
import numpy as np
array=np.array([0,1,2,3,4,5])
print(array[1]) # вывод элемента массива с индексом 1
print(array[1:3]) # вывод подмассива с помощью среза

1
[1 2]


In [ ]:
5. Примеры векторных операций и базовых статистик:

In [39]:
import numpy as np
array1=np.array([1,3,8,10])
array2=np.array([1,2,8,6])
print(array1+array2) # поэлементное сложение массивов
print(array1*array2) # поэлементное умножение массивов
print(np.mean(array1)) # вычисление средней величины 1 массива
print(np.mean(array2))# вычесление средней веоичины 2 массива

[ 2  5 16 16]
[ 1  6 64 60]
5.5
4.25
